In [2]:
import pandas as pd

# Load the dataset (replace 'your_dataset.csv' with the actual file name)
df = pd.read_csv('spotify_datasets/top_10000_1950-now.csv')

# View the first few rows of the dataset
df.head()
df.describe()

,Disc Number,Track Number,Track Duration (ms),Popularity,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature,Album Genres
count,10000.000000,10000.000000,1.000000e+04,10000.000000,9995.000000,9995.000000,9995.000000,9995.00000,9995.000000,9995.000000,9995.000000,9995.000000,9995.000000,9995.000000,9995.000000,9995.000000,0.0
mean,1.033200,4.938400,2.241931e+05,32.548200,0.608355,0.684050,5.171686,-7.25158,0.698249,0.065028,0.208264,0.029431,0.185236,0.586313,121.530226,3.960280,NaN
std,0.310978,5.464576,5.418227e+04,27.528964,0.145727,0.191107,3.583496,3.27837,0.459041,0.061050,0.248940,0.123842,0.148270,0.238929,26.231119,0.248113,NaN
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000020,0.000000,-29.36800,0.000000,0.000000,0.000003,0.000000,0.012000,0.000000,0.000000,0.000000,NaN
25%,1.000000,1.000000,1.920728e+05,0.000000,0.515500,0.561000,2.000000,-9.01900,0.000000,0.033100,0.018200,0.000000,0.089150,0.399500,102.776500,4.000000,NaN
50%,1.000000,3.000000,2.194130e+05,34.000000,0.618000,0.713000,5.000000,-6.49500,1.000000,0.042900,0.095300,0.000006,0.127000,0.599000,120.753000,4.000000,NaN
75%,1.000000,7.000000,2.498162e+05,57.000000,0.710000,0.836000,8.000000,-4.87800,1.000000,0.067550,0.317000,0.000569,0.245000,0.783000,134.307000,4.000000,NaN
max,15.000000,93.000000,1.561133e+06,94.000000,0.988000,0.997000,11.000000,2.76900,1.000000,0.711000,0.991000,0.985000,0.989000,0.995000,217.913000,5.000000,NaN